/**
 * Builds the tech-stack logo marks.   npm run assets:tools
 *
 * Each tool in TOOLS that has a brand mark in Simple Icons (CC0, a devDependency) gets its 24×24 SVG
 * path copied into src/lib/generated/tool-icons.ts, so the page ships only the ~20 paths it uses and
 * no icon library. Tools with no mark there (the AWS services, which Simple Icons removed, and the
 * generic "REST APIs") are drawn with Lucide pictograms by ToolIcon instead.
 */
import { writeFileSync } from "node:fs";
import * as simpleIcons from "simple-icons";
import { TOOLS } from "../../src/lib/data.ts";
import type { ToolId } from "../../src/lib/types/content.ts";
import { fromRoot } from "../lib/paths.mts";

const OUT = fromRoot("src/lib/generated/tool-icons.ts");

/** ToolId → Simple Icons export. Absent ids fall back to ToolIcon's Lucide pictograms. */
const SLUGS: Partial<Record<ToolId, keyof typeof simpleIcons>> = {
  nextjs: "siNextdotjs",
  typescript: "siTypescript",
  express: "siExpress",
  tailwind: "siTailwindcss",
  gsap: "siGsap",
  // Framer Motion's own mark isn't in Simple Icons; Framer's is the library's parent brand.
  "framer-motion": "siFramer",
  daisyui: "siDaisyui",
  zod: "siZod",
  supabase: "siSupabase",
  postgresql: "siPostgresql",
  prisma: "siPrisma",
  "react-query": "siReactquery",
  "socket-io": "siSocketdotio",
  contentful: "siContentful",
  cloudinary: "siCloudinary",
  git: "siGit",
  vercel: "siVercel",
  "upstash-redis": "siUpstash",
};

const entries = TOOLS.flatMap(({ id }) => {
  const key = SLUGS[id];
  if (!key) return [];
  const icon = simpleIcons[key] as { title: string; path: string } | undefined;
  if (!icon) throw new Error(`Simple Icons has no ${String(key)} (for ${id})`);
  return [`  ${JSON.stringify(id)}: { title: ${JSON.stringify(icon.title)}, path: ${JSON.stringify(icon.path)} },`];
});

writeFileSync(
  OUT,
  `// Generated by scripts/assets/build-tool-icons.mts (npm run assets:tools) from Simple Icons (CC0). Do not edit.

import type { ToolId } from "@/lib/types";

/** Brand marks as 24×24 SVG paths, drawn in currentColor by ToolIcon. Tools not listed use a Lucide pictogram. */
export const TOOL_ICONS: Partial<Record<ToolId, { title: string; path: string }>> = {
${entries.join("\n")}
};
`,
);
console.log(`${entries.length} marks → ${OUT}`);
